version: "3.8"

services:
    nginx:
        image: nginx:1.25.3
        volumes:
          - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - api00
          - api01
        ports:
          - "9999:9999"
        deploy:
           resources:
            limits:
              cpus: '0.1'
              memory: '20MB'
    
    api00: &api
        container_name: "api00"
        build: .
        expose:
        - "8080"
        depends_on:
        - db
        networks:
        - default
        deploy:
          resources:
            limits:
              cpus: "0.2"
              memory: "100MB"
        environment:
        - SHARD=0

    api01: 
        container_name: "api01"
        build: .
        expose:
        - "8080"
        depends_on:
        - db
        networks:
        - default
        deploy:
          resources:
            limits:
              cpus: "0.2"
              memory: "100MB"
        environment:
        - SHARD=1
   
    db:
        image: postgres:16.1
        hostname: db
        environment:
          - POSTGRES_PASSWORD=TheP@ssw0rd!
          - POSTGRES_USER=theuser
          - POSTGRES_DB=rinha
        volumes:
          - ./config/script.sql:/docker-entrypoint-initdb.d/script.sql
          - ./config/postgres.conf:/docker-entrypoint-initdb.d/postgres.conf
        networks:
        - default
        ports: 
        - 5432:5432
        command: postgres -c max_connections=50
        deploy:
          resources:
            limits:
              cpus: "1.0"
              memory: "330MB"

networks:
  default:
    driver: bridge
    name: rinha